# Generated by Django 5.1.4 on 2025-01-08 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRUD_based_on_forms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
