# Generated by Django 5.1.4 on 2025-01-08 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CRUD_based_on_forms', '0002_alter_orders_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='picture',
        ),
    ]
